openapi: 3.0.1
info:
  title: Rotten tomatoes
  description: Endpoints
  version: '1.0'
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Post login
      operationId: postLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /register:
    post:
      tags:
        - Auth
      summary: Post register
      operationId: postRegister
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /user:
    get:
      tags:
        - User
      summary: Get user
      operationId: getUser
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithReviewsDTO'

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /user/{id}:
    get:
      tags:
        - User
      summary: Get user with id
      operationId: getUserWithId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithReviewsDTO'

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /content/latest:
    get:
      tags:
        - Content
      summary: Get content latest
      operationId: getContentLatest
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultSimpleMoviesDTO'

  /content/top:
    get:
      tags:
        - Content
      summary: Get content top
      operationId: getContentTop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultSimpleMoviesDTO'

  /content/{id}:
    get:
      tags:
        - Content
      summary: Get content with id
      operationId: getContentWithId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDTO'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

    post:
      tags:
        - Review
      summary: Post content with id
      operationId: postContentWithId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleReviewDTO'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /categories:
    get:
      tags:
        - Categories
      summary: Get categories
      operationId: getCategories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultCategoriesDTO'

  /categories/{id}:
    get:
      tags:
        - Content
      summary: Get categories with id
      operationId: getCategoriesWithId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultSimpleMoviesDTO'

components:
  schemas:
    UserLoginDTO:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserDTO:
      required:
        - email
        - id
        - image
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
        email:
          type: string
    ErrorDTO:
      required:
        - message
      type: object
      properties:
        message:
          type: string
    UserRegisterDTO:
      required:
        - email
        - image
        - name
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        image:
          type: string
        name:
          type: string
    Category:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    SimpleMovieDTO:
      required:
        - categories
        - description
        - id
        - poster
        - score
        - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        poster:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        score:
          type: integer
          format: int32
    SimpleReviewDTO:
      required:
        - id
        - movie
        - stars
        - text
        - user
      type: object
      properties:
        id:
          type: string
        user:
          $ref: '#/components/schemas/UserDTO'
        movie:
          $ref: '#/components/schemas/SimpleMovieDTO'
        text:
          type: string
        stars:
          type: integer
          format: int32
    UserWithReviewsDTO:
      required:
        - email
        - id
        - image
        - name
        - reviews
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
        email:
          type: string
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/SimpleReviewDTO'
    ResultSimpleMoviesDTO:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/SimpleMovieDTO'
    MovieDTO:
      required:
        - categories
        - description
        - id
        - poster
        - relatedContent
        - reviews
        - score
        - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        poster:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        relatedContent:
          type: array
          items:
            $ref: '#/components/schemas/SimpleMovieDTO'
        score:
          type: integer
          format: int32
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/SimpleReviewDTO'
    ReviewDTO:
      required:
        - stars
        - text
      type: object
      properties:
        text:
          type: string
        stars:
          type: integer
          format: int32
    ResultCategoriesDTO:
      required:
        - result
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/Category'
